export const LANGUAGES = [
    { label: "Afrikaans", code: "af" },
    { label: "Albanian", code: "sq" },
    { label: "Amharic", code: "am" },
    { label: "Arabic", code: "ar" },
    { label: "Armenian", code: "hy" },
    { label: "Assamese", code: "as" },
    { label: "Azerbaijani", code: "az" },
    { label: "Basque", code: "eu" },
    { label: "Bengali", code: "bn" },
    { label: "Bulgarian", code: "bg" },
    { label: "Burmese", code: "my" },
    { label: "Catalan", code: "ca" },
    { label: "Cherokee", code: "chr" },
    { label: "Chinese (Hong Kong)", code: "zh-HK" },
    { label: "Chinese (Simplified)", code: "zh-CN" },
    { label: "Chinese (Traditional)", code: "zh-TW" },
    { label: "Croatian", code: "hr" },
    { label: "Czech", code: "cs" },
    { label: "Danish", code: "da" },
    { label: "Dutch", code: "nl" },
    { label: "English (UK)", code: "en-GB" },
    { label: "English (US)", code: "en" },
    { label: "Estonian", code: "et" },
    { label: "Filipino", code: "fil" },
    { label: "Finnish", code: "fi" },
    { label: "French", code: "fr" },
    { label: "French (Canada)", code: "fr-CA" },
    { label: "Galician", code: "gl" },
    { label: "Georgian", code: "ka" },
    { label: "German", code: "de" },
    { label: "Greek", code: "el" },
    { label: "Gujarati", code: "gu" },
    { label: "Hebrew", code: "iw" },
    { label: "Hindi", code: "hi" },
    { label: "Hungarian", code: "hu" },
    { label: "Icelandic", code: "is" },
    { label: "Indonesian", code: "id" },
    { label: "Irish", code: "ga" },
    { label: "Italian", code: "it" },
    { label: "Japanese", code: "ja" },
    { label: "Kannada", code: "kn" },
    { label: "Kazakh", code: "kk" },
    { label: "Khmer", code: "km" },
    { label: "Korean", code: "ko" },
    { label: "Lao", code: "lo" },
    { label: "Latvian", code: "lv" },
    { label: "Lithuanian", code: "lt" },
    { label: "Macedonian", code: "mk" },
    { label: "Malay", code: "ms" },
    { label: "Malayalam", code: "ml" },
    { label: "Marathi", code: "mr" },
    { label: "Mongolian", code: "mn" },
    { label: "Nepali", code: "ne" },
    { label: "Norwegian", code: "no" },
    { label: "Odia", code: "or" },
    { label: "Persian", code: "fa" },
    { label: "Polish", code: "pl" },
    { label: "Portuguese (Brazil)", code: "pt-BR" },
    { label: "Portuguese (Portugal)", code: "pt-PT" },
    { label: "Punjabi", code: "pa" },
    { label: "Romanian", code: "ro" },
    { label: "Russian", code: "ru" },
    { label: "Serbian", code: "sr" },
    { label: "Sinhala", code: "si" },
    { label: "Slovak", code: "sk" },
    { label: "Slovenian", code: "sl" },
    { label: "Spanish", code: "es" },
    { label: "Spanish (Latin America)", code: "es-419" },
    { label: "Swahili", code: "sw" },
    { label: "Swedish", code: "sv" },
    { label: "Tamil", code: "ta" },
    { label: "Telugu", code: "te" },
    { label: "Thai", code: "th" },
    { label: "Turkish", code: "tr" },
    { label: "Ukrainian", code: "uk" },
    { label: "Urdu", code: "ur" },
    { label: "Uzbek", code: "uz" },
    { label: "Vietnamese", code: "vi" },
    { label: "Welsh", code: "cy" },
    { label: "Zulu", code: "zu" }
];
